name: OpenAPI Specification Validation

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7.0.0
        with:
          node-version: '20'

      - name: Install Linter
        run: npm install @redocly/cli -g

      - name: Validate OpenAPI Specification
        run: redocly lint ./xkcd-data-hub-api.yaml --format=stylish

  dependabot_auto_merge:
    needs: validate
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      contents: write
      pull-requests: write
    uses: yonatankarp/github-actions/.github/workflows/dependabot-auto-merge.yml@v2
    secrets:
      GITHUB_PAT: ${{ secrets.REVIEWER_GITHUB_TOKEN }}
